Repository stroeer/terraform-aws-ecs-fargate, pull requests merged in 2022-12, with the labels that each got.

#81 Add support for capacity providers by using tf 1.3 optional object parmeters
  .github/workflows/workflow.yaml
  README.md
  docs/part2.md
  main.tf
  variables.tf
  versions.tf
Labels: enhancement, dependencies

#82 feat: added pr title validation for automatic release notes
  .github/CODEOWNERS
  .github/workflows/pr-title.yaml
  .github/workflows/static-analysis.yaml
  .pre-commit-config.yaml
  README.md
  docs/part1.md
  docs/part2.md
Labels: documentation, enhancement

#86 fix(deployment): adjusted python version according to build image
  modules/deployment/code_build.tf
Labels: bug
