Repository stroeer/terraform-aws-ecs-fargate, pull requests merged in 2024-01, with the labels that each got.

#125 feat: expose the CodeBuild CW Log retention period
  README.md
  main.tf
  modules/deployment/code_build.tf
  modules/deployment/variables.tf
  variables.tf
Labels: enhancement

#131 chore: bumped tflint ruleset and gh action for tf
  .github/workflows/static-analysis.yaml
  .pre-commit-config.yaml
  .tflint.hcl
Labels: dependencies

#132 feat: use Lambda aarch64 architecture as default for CodeBuild
  README.md
  main.tf
  modules/deployment/backend.tf
  modules/deployment/code_build.tf
  modules/deployment/variables.tf
  variables.tf
Labels: enhancement

#135 feat: support CodePipeline V2
  README.md
  main.tf
  modules/deployment/code_pipeline.tf
  modules/deployment/variables.tf
  variables.tf
  versions.tf
Labels: enhancement

#136 chore: use trivy instead of tfsec
  .github/workflows/static-analysis.yaml
  .pre-commit-config.yaml
  examples/fixtures/context/Dockerfile
Labels: enhancement, dependencies
